services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: ixemgod/php_wikipedia_scrapper:latest
    container_name: apache-php
    ports:
      - "8082:80"  # Port modifié pour éviter les conflits avec un Apache local
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  mysql:
    image: ixemgod/mysql_wikipedia_scrapper:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wikipedia
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"  # Port modifié

  phpmyadmin:
    image: ixemgod/phpmyadmin_wikipedia_scrapper:latest
    container_name: phpmyadmin
    ports:
      - "9090:80"  # Port modifié
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: userpassword
    networks:
      - app-network

networks:
  app-network:
    name: wikipedia-scrapper_app-network
    driver: bridge

volumes:
  mysql-data:
